server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.182.82:3306/practice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: dev
    password: a123456
    cachePrepStmts: true
  redis:
    port: 6379
    host: 112.74.182.82
logging:
  level:
    com.prescription.memory.dao: debug
swagger:
  enable: true