server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123
    cachePrepStmts: true
logging:
  level:
    com.prescription.memory.dao: debug
swagger:
  enable: true
