server:
  port: 8080
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package:
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
    cachePrepStmts: true

